### ISSUE TITLE
Package list not updated

### ISSUE THREAD

**Issue by MiroHibler** [rissem/meteorpad#10]
Great app! :)

But newly/updated packages do not show in the list.

How much time does it take for a package to appear on the list?

**Comment by rissem** [comment]
Thanks! Right now updating packages is a manual process, but it should be automatic soon.

I'll run an update here soon, so you can have the latest.

**Comment by MiroHibler** [comment]
Thanks! :)

**Comment by MiroHibler** [comment]
It seems to be working fine now - I updated a package and new version appeared immediately!

Great work BTW :)

Thanks again!
