### ISSUE TITLE
How can I force a refresh?

### ISSUE THREAD

**Issue by dandv** [rissem/meteorpad#13]
I've forked the [blank example](http://meteorpad.com/pad/57dsfZ7jYjErfzR8A/Reactive%20vars) and changed "Hello world" to "Hello Earth". It's been a few minutes and the pad hasn't updates. Either the server is very slow, or there needs to be a button to trigger a manual app refresh.

Same for [this pad](http://meteorpad.com/pad/BHJG6jBZCkvB78HoE/Leaderboard). The app refreshed after removing packages, but not after changing the JS and HTML.

Sorry to say, but Meteorpad is rather unable for me as of now.

**Comment by rissem** [comment]
Hey @dandv, both of those examples are unbearably slow. Things are quite a bit faster now with the newer Meteor versions; if you could give it a second chance I'd appreciate it.

[Blank Pad](http://meteorpad.com/pad/qob2vEAHqZ2xoGnJL/Reactive_Vars_1.1.0.2])

[Leaderboard](http://meteorpad.com/pad/v25Ea4yjtJf4THaSL/Leaderboard)
