### ISSUE TITLE
Using meteorhacks:npm on meteorpad?

### ISSUE THREAD

**Issue by jakobloekke** [rissem/meteorpad#14]
Hi,

Is it possible to use the meteorhacks:npm package on meteorpad?

kind regards,
Jakob

**Comment by rissem** [comment]
Currently not, meteorhacks:npm relies on an extra file `packages.json` to record the NPM dependencies of the project. MeteorPad is only aware of [main.html, common.js, server/app.js, client/app.js and style.css]. This may change in the future, but it's not a high priority right now.
