### ISSUE TITLE
Non-leaderboard base

### ISSUE THREAD

**Issue by richsilv** [rissem/meteorpad#2]
Is there a way to fork something other than the leaderboard example, like the default "click me" app?  If not, could you add it?

Deleting all the unnecessary code in the leaderboard example is genuinely a significant factor in discouraging me (and, I imagine, others) from using MeteorPad - I would far rather just start with the most minimal possible base.

**Comment by dandv** [comment]
:+1:. Can that link to the blank pad be made available somewhere in the MeteorPad UI?
