### ISSUE TITLE
MyPad is disabled.

### ISSUE THREAD

**Issue by rvolari** [rissem/meteorpad#3]
Hi,
(sorry to post a support question here - not sure where else I should be posting)
I watched the videos you have online about MeteorPad, I have to say it is very impressive:)
I tried using it but it only allows me to use the Leaderboard example? what am I doing wrong
I signed up for Meteor Developer account and that did not seem to be able to give me access either.
Thanks in advance
Great work
I like it

**Comment by tutaslabs** [comment]
i think there are some issues. it appears the docker instances are not getting created. rvolari - if you get the leaderboard to load and display, you must then save a copy in order to make changes. if you are logged into meteor dev, this copy will go into your account under MyPads.

**Comment by rissem** [comment]
@rvolari You are posting in the right spot. Thanks for the feedback! Currently everyone starts from Leaderboard, but you're able to turn it into whatever you want (and rename it by clicking the title). Let me know if you're still having issues. At some point I'd like to provide some other "starter pads"

@tutaslabs Thanks for the quick response. You're exactly right; there was an issue a few days ago that prevented the docker containers from booting. Great to hear that you're using it to teach a course. I'm curious to hear how that goes.
