### ISSUE TITLE
MeteorPad Down/Lagging-Out

### ISSUE THREAD

**Issue by abernix** [rissem/meteorpad#43]
I don't know how long this has been going on before this, but for the last week or so – MeteorPad has been down every time I've checked it.

It's frequently an invaluable tool in #meteor on IRC, so just thought I'd point it out.

Holler if you need some help I guess. :smile:

**Comment by rissem** [comment]
Thanks @abernix. I restarted one of the servers and it's back now. Great to hear that it's been valuable for you. Let me know if you run into anything else.

**Comment by abernix** [comment]
Cheers mate.  Thanks so much for the prompt answer too.

Yea, can't say I personally need it a lot, but it's so stupid-helpful when someone pops in #meteor and is trying to explain some-broke-thing and we're stuck trying to piece together all the silly gists/pastebins that they paste into the chatroom. :)

Cheers again hey.

**Comment by abernix** [comment]
Looks like the the "Server" still isn't starting?  (Bottom part just spins black) and HTML preview never loads.

**Comment by rissem** [comment]
Back now. Thanks for being my monitoring service for the past couple days :-)

**Comment by abernix** [comment]
lol.  Anytime. :)

**Comment by BrooklynC** [comment]
Has this issue popped up again? I'm just getting a spinner in the console, doesn't even try to load.  Been a couple days now.  MeteorPad is the only way I am able to articulate my newbie questions on Q&A forums.

**Comment by rissem** [comment]
Yeah, thanks @BrooklynC for letting me know. Fixed now.

**Comment by BrooklynC** [comment]
Thanks!
