### ISSUE TITLE
Save/Fork buttons not available when logged in

### ISSUE THREAD

**Issue by garrilla** [rissem/meteorpad#5]
Save/Fork buttons not available when logged in with Meteor Dev account

this is chrome desktop Version 39.0.2171.95 (64-bit)

**Comment by rissem** [comment]
Thanks for reporting @garrilla. This is probably because the pad isn't owned by your account. If you "Save Copy", then you should be able to save and fork the pad. Let me know if you're still having issues.

**Comment by garrilla** [comment]
sorry, took a while to get back...

please see the screencap - you can see I'm logged in, but have no buttons

![image](https://cloud.githubusercontent.com/assets/5795139/5774941/acb4db1a-9d6b-11e4-8652-1463b7f48a24.png)

**Comment by brylie** [comment]
I am experiencing this issue with Chrome 39, Chromium 37, and Firefox 34 on Ubuntu 14.10. When I log in, the buttons flash briefly then disappear.

Removing 'float: right' from the '.pad-actions' div seems to resolve the issue.
