### ISSUE TITLE
Allow user to specify version of meteor package

### ISSUE THREAD

**Issue by mongoh** [rissem/meteorpad#6]
I am trying to get the latest version of autoform, but Meteorpad is installing: 

`aldeed:autoform  added, version 3.2.0`

**Comment by rissem** [comment]
What is the latest version? Could you send me a link to your pad?

**Comment by mongoh** [comment]
@rissem The latest version for autoform is 4.2.2
Thanks!

**Comment by rissem** [comment]
Hmm, for me it just added 4.2.1 when I didn't specify a version.

You actually are able to specify the version when entering your package name (i.e. `aldeed:autoform@3.2.0`)

Here's an example of a pad that does just that.
http://meteorpad.com/pad/7A34PafR2R9FgRsJs/Leaderboard

I really need to make it more clear that the version can be specified. Let me know if you have any ideas on that front.

**Comment by mongoh** [comment]
I tried specifying the version number, as you specified, and it did not work. I hit enter, and no action.

Maybe a tooltip over the package field with a few details?
