### ISSUE TITLE
issues in Firefox

### ISSUE THREAD

**Issue by neocris** [rissem/meteorpad#7]
the action buttons don´t show, and when switching to Meteor 0.8.3 after adding standard-app-packages and mongo packages it still gives an "no such package: 'mongo'" error. i'm using win xp

**Comment by rissem** [comment]
Could you post a link to your pad?

**Comment by neocris** [comment]
sorry for the delay.
source: http://meteorpad.com/pad/WeWX6MPaJxNbTndbY/Leaderboard
run: http://app-6nhqfarg.meteorpad.com/

**Comment by rissem** [comment]
Sorry for not getting back to you sooner. Mongo isn't a package in 0.8.3

Here's a fork of your pad made to work with 0.8.3.

http://meteorpad.com/pad/hpaqQv6DWmDbWKjjc/Copy%20of%20Leaderboard
