### ISSUE TITLE
Download and Save buttons not visible (.pad-actions div)

### ISSUE THREAD

**Issue by brylie** [rissem/meteorpad#9]
In Firefox 34 and Chromium 39 on Ubuntu 14.10, the pads are not reloading when I change code. Is there a button or keyboard combination that I am supposed to use to save the contents of the pad?

tl;dr
-----
Remove the `float: right;` from `.pad-actions` to restore the button visibility.

**Comment by brylie** [comment]
Issue #5 may still be causing trouble. I cannot see the save buttons on the aforementioned browsers, so was confused when the code failed to save.

**Comment by brylie** [comment]
Also note, this CSS bug only happens when a user is logged in. Simply remove the `float: right;` from `.pad-actions` to restore the button visibility.

**Comment by mmcintosh** [comment]
I can confirm this is still happening for me Ubuntu 14.04 Firefox version 35.0.1 and Chrome Version 40.0.2214.111 (64-bit)

**Comment by brylie** [comment]
How can we patch this issue?

**Comment by martinhbramwell** [comment]
+1

**Comment by martinhbramwell** [comment]
Thanks to Siyfion, for pointing out to me that <Ctrl-s> is intercepted and will save changes within Meteorpad, not to local storage.

**Comment by brylie** [comment]
@martinhbramwell thanks for that shortcut!

It still seems like this issue needs attention, and possibly testing on multiple screen resolutions.

**Comment by buhrmad** [comment]
Bug still occurs in Windows 7 Chrome Version 41.0.2272.101 m.  <CTRL-S> does work.

**Comment by brylie** [comment]
@rissem any response on this issue?

**Comment by rissem** [comment]
I believe I resolved this a couple weeks ago. Please reopen if you're still able to reproduce.

**Comment by brylie** [comment]
Thanks @rissem :-)
